version: "3"

services:
  app_superset:        
    restart: on-failure:5
    build: .
    container_name: app_superset
    ports:
      - "8089:8089"
    command:        
      "gunicorn 'superset.app:create_app()' -b 0.0.0.0:8089"